package com.web.lms.model;
// Generated Mar 27, 2018 11:06:48 PM by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LmsClass generated by hbm2java
 */
@Entity
@Table(name = "lms_class", catalog = "lmsdb")
public class LmsClass implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private Set<LmsDesignation> lmsDesignations = new HashSet<LmsDesignation>(0);
	private Set<LmsWftRequestSelector> lmsWftRequestSelectors = new HashSet<LmsWftRequestSelector>(0);

	public LmsClass() {
	}

	public LmsClass(String name, Set<LmsDesignation> lmsDesignations,
			Set<LmsWftRequestSelector> lmsWftRequestSelectors) {
		this.name = name;
		this.lmsDesignations = lmsDesignations;
		this.lmsWftRequestSelectors = lmsWftRequestSelectors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lmsClass")
	public Set<LmsDesignation> getLmsDesignations() {
		return this.lmsDesignations;
	}

	public void setLmsDesignations(Set<LmsDesignation> lmsDesignations) {
		this.lmsDesignations = lmsDesignations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lmsClass")
	@JsonIgnore
	public Set<LmsWftRequestSelector> getLmsWftRequestSelectors() {
		return this.lmsWftRequestSelectors;
	}

	public void setLmsWftRequestSelectors(Set<LmsWftRequestSelector> lmsWftRequestSelectors) {
		this.lmsWftRequestSelectors = lmsWftRequestSelectors;
	}

}
