package com.web.lms.model;
// Generated Apr 25, 2018 9:23:29 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmsDepartment generated by hbm2java
 */
@Entity
@Table(name = "lms_department", catalog = "lmsdb")
public class LmsDepartment implements java.io.Serializable {

	private Integer id;
	private LmsDivision lmsDivision;
	private String name;
	private Date insertDate;
	private Integer insertBy;
	private Date updateDate;
	private Integer updateBy;
	private Set<LmsSection> lmsSections = new HashSet<LmsSection>(0);
	private Set<LmsUser> lmsUsers = new HashSet<LmsUser>(0);

	public LmsDepartment() {
	}

	public LmsDepartment(LmsDivision lmsDivision, String name, Date insertDate, Integer insertBy, Date updateDate,
			Integer updateBy, Set<LmsSection> lmsSections, Set<LmsUser> lmsUsers) {
		this.lmsDivision = lmsDivision;
		this.name = name;
		this.insertDate = insertDate;
		this.insertBy = insertBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.lmsSections = lmsSections;
		this.lmsUsers = lmsUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "DIVISION_ID")
	public LmsDivision getLmsDivision() {
		return this.lmsDivision;
	}

	public void setLmsDivision(LmsDivision lmsDivision) {
		this.lmsDivision = lmsDivision;
	}

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATE", length = 19)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Column(name = "INSERT_BY")
	public Integer getInsertBy() {
		return this.insertBy;
	}

	public void setInsertBy(Integer insertBy) {
		this.insertBy = insertBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lmsDepartment")
	public Set<LmsSection> getLmsSections() {
		return this.lmsSections;
	}

	public void setLmsSections(Set<LmsSection> lmsSections) {
		this.lmsSections = lmsSections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lmsDepartment")
	public Set<LmsUser> getLmsUsers() {
		return this.lmsUsers;
	}

	public void setLmsUsers(Set<LmsUser> lmsUsers) {
		this.lmsUsers = lmsUsers;
	}

}
