package com.web.lms.model;
// Generated Jul 8, 2018 10:37:31 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmsEventLog generated by hbm2java
 */
@Entity
@Table(name = "lms_event_log", catalog = "supremet_lmsdb")
public class LmsEventLog implements java.io.Serializable {

	private Integer id;
	private Integer userId;
	private String userName;
	private String pageName;
	private String eventDescription;
	private Date eventTime;

	public LmsEventLog() {
	}

	public LmsEventLog(Integer userId, String userName, String pageName, String eventDescription, Date eventTime) {
		this.userId = userId;
		this.userName = userName;
		this.pageName = pageName;
		this.eventDescription = eventDescription;
		this.eventTime = eventTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "USER_ID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "USER_NAME", length = 50)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "PAGE_NAME", length = 50)
	public String getPageName() {
		return this.pageName;
	}

	public void setPageName(String pageName) {
		this.pageName = pageName;
	}

	@Column(name = "EVENT_DESCRIPTION", length = 2000)
	public String getEventDescription() {
		return this.eventDescription;
	}

	public void setEventDescription(String eventDescription) {
		this.eventDescription = eventDescription;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "EVENT_TIME", length = 19)
	public Date getEventTime() {
		return this.eventTime;
	}

	public void setEventTime(Date eventTime) {
		this.eventTime = eventTime;
	}

}
