package com.web.lms.model;
// Generated Mar 26, 2018 12:32:28 AM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LmsTmplWfRole generated by hbm2java
 */
@Entity
@Table(name = "lms_tmpl_wf_role", catalog = "lmsdb")
public class LmsTmplWfRole implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private Date insertDate;
	private Integer insertBy;
	private Date updateDate;
	private Integer updateBy;
	private Set<LmsTmplRequestHopsRoleMap> lmsTmplRequestHopsRoleMaps = new HashSet<LmsTmplRequestHopsRoleMap>(0);

	public LmsTmplWfRole() {
	}

	public LmsTmplWfRole(String roleName, Date insertDate, Integer insertBy, Date updateDate, Integer updateBy,
			Set<LmsTmplRequestHopsRoleMap> lmsTmplRequestHopsRoleMaps) {
		this.roleName = roleName;
		this.insertDate = insertDate;
		this.insertBy = insertBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.lmsTmplRequestHopsRoleMaps = lmsTmplRequestHopsRoleMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ROLE_NAME", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATE", length = 19)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Column(name = "INSERT_BY")
	public Integer getInsertBy() {
		return this.insertBy;
	}

	public void setInsertBy(Integer insertBy) {
		this.insertBy = insertBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lmsTmplWfRole")
	@JsonIgnore
	public Set<LmsTmplRequestHopsRoleMap> getLmsTmplRequestHopsRoleMaps() {
		return this.lmsTmplRequestHopsRoleMaps;
	}

	public void setLmsTmplRequestHopsRoleMaps(Set<LmsTmplRequestHopsRoleMap> lmsTmplRequestHopsRoleMaps) {
		this.lmsTmplRequestHopsRoleMaps = lmsTmplRequestHopsRoleMaps;
	}

}
