package com.web.lms.model;
// Generated May 31, 2018 6:04:48 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmsWfRequestHop generated by hbm2java
 */
@Entity
@Table(name = "lms_wf_request_hop", catalog = "supremet_lmsdb")
public class LmsWfRequestHop implements java.io.Serializable {

	private Integer id;
	private LmsUser lmsUser;
	private LmsWfRequest lmsWfRequest;
	private LmsWftRequestHopRolePageMap lmsWftRequestHopRolePageMap;
	private Integer wftRoleId;
	private Date startDate;
	private Date endDate;
	private String status;
	private Integer userId;
	private Date insertDate;
	private Integer insertBy;
	private Date updateDate;
	private Integer pageId;

	public LmsWfRequestHop() {
	}

	public LmsWfRequestHop(LmsUser lmsUser, LmsWfRequest lmsWfRequest,
			LmsWftRequestHopRolePageMap lmsWftRequestHopRolePageMap, Integer wftRoleId, Date startDate, Date endDate,
			String status, Integer userId, Date insertDate, Integer insertBy, Date updateDate, Integer pageId) {
		this.lmsUser = lmsUser;
		this.lmsWfRequest = lmsWfRequest;
		this.lmsWftRequestHopRolePageMap = lmsWftRequestHopRolePageMap;
		this.wftRoleId = wftRoleId;
		this.startDate = startDate;
		this.endDate = endDate;
		this.status = status;
		this.userId = userId;
		this.insertDate = insertDate;
		this.insertBy = insertBy;
		this.updateDate = updateDate;
		this.pageId = pageId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "UPDATE_BY")
	public LmsUser getLmsUser() {
		return this.lmsUser;
	}

	public void setLmsUser(LmsUser lmsUser) {
		this.lmsUser = lmsUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "WF_REQUEST_ID")
	public LmsWfRequest getLmsWfRequest() {
		return this.lmsWfRequest;
	}

	public void setLmsWfRequest(LmsWfRequest lmsWfRequest) {
		this.lmsWfRequest = lmsWfRequest;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "WFT_HOPS_ID")
	public LmsWftRequestHopRolePageMap getLmsWftRequestHopRolePageMap() {
		return this.lmsWftRequestHopRolePageMap;
	}

	public void setLmsWftRequestHopRolePageMap(LmsWftRequestHopRolePageMap lmsWftRequestHopRolePageMap) {
		this.lmsWftRequestHopRolePageMap = lmsWftRequestHopRolePageMap;
	}

	@Column(name = "WFT_ROLE_ID")
	public Integer getWftRoleId() {
		return this.wftRoleId;
	}

	public void setWftRoleId(Integer wftRoleId) {
		this.wftRoleId = wftRoleId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "START_DATE", length = 19)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "END_DATE", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "USER_ID")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATE", length = 19)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Column(name = "INSERT_BY")
	public Integer getInsertBy() {
		return this.insertBy;
	}

	public void setInsertBy(Integer insertBy) {
		this.insertBy = insertBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "PAGE_ID")
	public Integer getPageId() {
		return this.pageId;
	}

	public void setPageId(Integer pageId) {
		this.pageId = pageId;
	}

}
