package com.web.lms.model;
// Generated May 19, 2018 10:54:22 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LmsWftRequestSelector generated by hbm2java
 */
@Entity
@Table(name = "lms_wft_request_selector", catalog = "supremet_lmsdb")
public class LmsWftRequestSelector implements java.io.Serializable {

	private Integer id;
	private LmsClass lmsClass;
	private LmsLeaveType lmsLeaveType;
	private LmsSection lmsSection;
	private LmsWftRequestType lmsWftRequestType;
	private Integer insertBy;
	private Date insertDate;
	private Integer updateBy;
	private Date updateDate;

	public LmsWftRequestSelector() {
	}

	public LmsWftRequestSelector(LmsClass lmsClass, LmsLeaveType lmsLeaveType, LmsSection lmsSection,
			LmsWftRequestType lmsWftRequestType, Integer insertBy, Date insertDate, Integer updateBy, Date updateDate) {
		this.lmsClass = lmsClass;
		this.lmsLeaveType = lmsLeaveType;
		this.lmsSection = lmsSection;
		this.lmsWftRequestType = lmsWftRequestType;
		this.insertBy = insertBy;
		this.insertDate = insertDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CLASS_ID")
	public LmsClass getLmsClass() {
		return this.lmsClass;
	}

	public void setLmsClass(LmsClass lmsClass) {
		this.lmsClass = lmsClass;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LEAVE_TYPE_ID")
	public LmsLeaveType getLmsLeaveType() {
		return this.lmsLeaveType;
	}

	public void setLmsLeaveType(LmsLeaveType lmsLeaveType) {
		this.lmsLeaveType = lmsLeaveType;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SECTION_ID")
	public LmsSection getLmsSection() {
		return this.lmsSection;
	}

	public void setLmsSection(LmsSection lmsSection) {
		this.lmsSection = lmsSection;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TRHR_MAP_ID")
	public LmsWftRequestType getLmsWftRequestType() {
		return this.lmsWftRequestType;
	}

	public void setLmsWftRequestType(LmsWftRequestType lmsWftRequestType) {
		this.lmsWftRequestType = lmsWftRequestType;
	}

	@Column(name = "INSERT_BY")
	public Integer getInsertBy() {
		return this.insertBy;
	}

	public void setInsertBy(Integer insertBy) {
		this.insertBy = insertBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATE", length = 19)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
