package com.web.lms.model;
// Generated Apr 28, 2018 3:31:02 PM by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * LmsWftRole generated by hbm2java
 */
@Entity
@Table(name = "lms_wft_role", catalog = "supremet_lmsdb")
public class LmsWftRole implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private Date insertDate;
	private Integer insertBy;
	private Date updateDate;
	private Integer updateBy;
	private Set<LmsWftRoleUserMap> lmsWftRoleUserMaps = new HashSet<LmsWftRoleUserMap>(0);
	private Set<LmsWftRequestHopRolePageMap> lmsWftRequestHopRolePageMaps = new HashSet<LmsWftRequestHopRolePageMap>(0);

	public LmsWftRole() {
	}

	public LmsWftRole(String roleName, Date insertDate, Integer insertBy, Date updateDate, Integer updateBy,
			Set<LmsWftRoleUserMap> lmsWftRoleUserMaps, Set<LmsWftRequestHopRolePageMap> lmsWftRequestHopRolePageMaps) {
		this.roleName = roleName;
		this.insertDate = insertDate;
		this.insertBy = insertBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.lmsWftRoleUserMaps = lmsWftRoleUserMaps;
		this.lmsWftRequestHopRolePageMaps = lmsWftRequestHopRolePageMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ROLE_NAME", length = 50)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERT_DATE", length = 19)
	public Date getInsertDate() {
		return this.insertDate;
	}

	public void setInsertDate(Date insertDate) {
		this.insertDate = insertDate;
	}

	@Column(name = "INSERT_BY")
	public Integer getInsertBy() {
		return this.insertBy;
	}

	public void setInsertBy(Integer insertBy) {
		this.insertBy = insertBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATE_DATE", length = 19)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@Column(name = "UPDATE_BY")
	public Integer getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(Integer updateBy) {
		this.updateBy = updateBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lmsWftRole")
	@JsonIgnore
	public Set<LmsWftRoleUserMap> getLmsWftRoleUserMaps() {
		return this.lmsWftRoleUserMaps;
	}

	public void setLmsWftRoleUserMaps(Set<LmsWftRoleUserMap> lmsWftRoleUserMaps) {
		this.lmsWftRoleUserMaps = lmsWftRoleUserMaps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lmsWftRole")
	@JsonIgnore
	public Set<LmsWftRequestHopRolePageMap> getLmsWftRequestHopRolePageMaps() {
		return this.lmsWftRequestHopRolePageMaps;
	}

	public void setLmsWftRequestHopRolePageMaps(Set<LmsWftRequestHopRolePageMap> lmsWftRequestHopRolePageMaps) {
		this.lmsWftRequestHopRolePageMaps = lmsWftRequestHopRolePageMaps;
	}

}
