package com.web.lms.model;
// Generated Mar 17, 2018 12:06:37 PM by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Myguests generated by hbm2java
 */
@Entity
@Table(name = "myguests", catalog = "lmsdb")
public class Myguests implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private String email;
	private Date regDate;

	public Myguests() {
	}

	public Myguests(String firstname, String lastname, Date regDate) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.regDate = regDate;
	}

	public Myguests(String firstname, String lastname, String email, Date regDate) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.regDate = regDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 30)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 30)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "reg_date", nullable = false, length = 19)
	public Date getRegDate() {
		return this.regDate;
	}

	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

}
